# Generated by Django 6.0.5 on 2026-05-30 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('diretor', models.CharField(max_length=200, verbose_name='Diretor')),
                ('ano_lancamento', models.IntegerField(verbose_name='Ano de Lançamento')),
                ('capa', models.ImageField(blank=True, null=True, upload_to='capas/', verbose_name='Capa do Filme')),
                ('capa_url', models.URLField(blank=True, null=True, verbose_name='URL da Capa')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmes', to='filmes.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Filme',
                'verbose_name_plural': 'Filmes',
                'ordering': ['titulo'],
            },
        ),
    ]
